services:
  postgres:
    image: postgres:15-alpine
    container_name: zima_postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-zima}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-rezazh79}
      DJANGO_ENV: production

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - zima_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-zima}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: zima_redis
    networks:
      - zima_network
    environment:
      DJANGO_ENV: production

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # کانتینر Django جداگانه برای دیباگ و توسعه
  django:
    build:
      context: .
      dockerfile: Dockerfile.gunicorn
    container_name: zima_django
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.production
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - DJANGO_ENV=development
    volumes:
      - ./:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./logs:/app/logs
    networks:
      - zima_network
    restart: unless-stopped
    ports:
      - "8001:8000"
    command: python manage.py runserver 0.0.0.0:8000

  # کانتینر Gunicorn اصلی
  gunicorn:
    build:
      context: .
      dockerfile: Dockerfile.gunicorn
    container_name: zima_gunicorn
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.production
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - DJANGO_ENV=production
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./logs:/app/logs
    networks:
      - zima_network
    restart: unless-stopped
    expose:
      - "8000"

  # nginx
  nginx:
    image: nginx:alpine
    container_name: zima_nginx
    depends_on:
      - gunicorn
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/zima.conf  # تغییر مسیر به فایل موجود
      - ./config/nginx.custom.conf:/etc/nginx/conf.d/01-custom.conf  # تغییر مسیر به فایل موجود
      - ./ssl:/etc/nginx/ssl:ro  # مسیر فایل‌های SSL
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
    networks:
      - zima_network
    environment:
      - NGINX_SERVER_NAMES_HASH_BUCKET_SIZE=64
    restart: unless-stopped

volumes:
  postgres_data:
    name: zima_postgres_data

networks:
  zima_network:
    name: zima_network