version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: zima_postgres
    environment:
      - POSTGRES_DB=${DB_NAME:-zima}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-rezazh79}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - zima_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-zima}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: zima_redis
    networks:
      - zima_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build: .
    container_name: zima_web
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - DJANGO_ENV=production
      - ALLOWED_HOSTS=zimabestshop.ir,www.zimabestshop.ir,localhost,127.0.0.1
    ports:
      - "80:80"  # برای HTTP
      - "443:443"  # برای HTTPS (اگر SSL دارید)
    volumes:
      - ./static:/app/staticfiles
      - ./media:/app/media
      - ./logs:/app/logs
      - ./ssl:/etc/nginx/ssl  # فعال کردن این خط

    networks:
      - zima_network
    restart: unless-stopped

volumes:
  postgres_data:
    name: zima_postgres_data

networks:
  zima_network:
    name: zima_network