services:
  postgres:
    image: postgres:15-alpine
    container_name: zima_postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-zima}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-rezazh79}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - zima_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-zima}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: zima_redis
    networks:
      - zima_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  db-cleanup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zima_db_cleanup
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.production
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - .:/app
    networks:
      - zima_network
    profiles:
      - cleanup
    command: python /app/config/migration_utils.py cleanup

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zima_django
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.production
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - DJANGO_ENV=development
      - SERVICE_TYPE=django
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./logs:/app/logs
    networks:
      - zima_network
    restart: unless-stopped
    ports:
      - "8002:8000" # فقط برای توسعه و دیباگ، gunicorn و daphne روی پورت‌های اصلی هستند

  gunicorn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zima_gunicorn
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.production
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - DJANGO_ENV=production
      - SERVICE_TYPE=gunicorn
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./logs:/app/logs
    networks:
      - zima_network
    restart: unless-stopped
    expose:
      - "8000"

  daphne:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zima_daphne
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.production
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - DJANGO_ENV=production
      - SERVICE_TYPE=daphne
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./logs:/app/logs
    networks:
      - zima_network
    restart: unless-stopped
    ports:
      - "8001:8001"
    command: [ "/entrypoint.sh", "daphne" ]

  nginx:
    image: nginx:alpine
    container_name: zima_nginx
    depends_on:
      - gunicorn
      - daphne
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
    networks:
      - zima_network
    environment:
      - NGINX_SERVER_NAMES_HASH_BUCKET_SIZE=128
    restart: unless-stopped

volumes:
  postgres_data:
    name: zima_postgres_data

networks:
  zima_network:
    name: zima_network