# Generated by Django 5.1.5 on 2025-06-11 14:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'پیام گفتگو', 'verbose_name_plural': 'پیام\u200cهای گفتگو'},
        ),
        migrations.AlterModelOptions(
            name='userstatus',
            options={'verbose_name': 'وضعیت آنلاین کاربر', 'verbose_name_plural': 'وضعیت\u200cهای آنلاین کاربران'},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='typing_in_room',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/%Y/%m/%d/', verbose_name='فایل پیوست'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'متن'), ('image', 'تصویر'), ('file', 'فایل'), ('system', 'سیستمی')], default='text', max_length=10, verbose_name='نوع پیام'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان خوانده شدن'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='داده\u200cهای اضافی'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='متن اعلان'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('chat', 'گفتگو'), ('system', 'سیستمی')], default='system', max_length=20, verbose_name='نوع اعلان'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین مشاهده'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.CharField(choices=[('online', 'آنلاین'), ('offline', 'آفلاین')], default='offline', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TemporaryFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='temp_files/%Y/%m/%d/', verbose_name='فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان آپلود')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_files', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فایل موقت',
                'verbose_name_plural': 'فایل\u200cهای موقت',
                'ordering': ['-created_at'],
            },
        ),
    ]
