# Generated by Django 5.1.5 on 2025-06-12 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_options_alter_userstatus_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='hidden_for_users',
            field=models.ManyToManyField(blank=True, help_text='کاربرانی که این گفتگو را حذف کرده\u200cاند و دیگر نمی\u200cبینند', related_name='hidden_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
