# Generated by Django 5.1.5 on 2025-06-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_closed_at_chatroom_is_closed_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
