# Generated by Django 5.1.5 on 2025-08-06 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_options_alter_userstatus_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلانها'},
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='hidden_for_users',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='typing_in_room',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='active_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'is_read', 'sender'], name='chat_chatme_room_id_c92a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='chat_chatme_created_888e17_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['user', 'status'], name='chat_chatro_user_id_da3ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['agent', 'status'], name='chat_chatro_agent_i_ad5c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['updated_at'], name='chat_chatro_updated_79f21c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='chat_notifi_user_id_7c95fc_idx'),
        ),
        migrations.AddIndex(
            model_name='userstatus',
            index=models.Index(fields=['status', 'last_seen'], name='chat_userst_status_ab9f7a_idx'),
        ),
    ]
