# Generated by Django 5.1.5 on 2025-08-09 09:27

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_notification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلان\u200cها'},
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_chatme_room_id_c92a4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_chatme_created_888e17_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatroom',
            name='chat_chatro_user_id_da3ba8_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatroom',
            name='chat_chatro_agent_i_ad5c0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatroom',
            name='chat_chatro_updated_79f21c_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='chat_notifi_user_id_7c95fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='userstatus',
            name='chat_userst_status_ab9f7a_idx',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='active_sessions',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='hidden_for_users',
            field=models.ManyToManyField(blank=True, help_text='کاربرانی که این گفتگو را حذف کرده\u200cاند و دیگر نمی\u200cبینند', related_name='hidden_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='typing_in_room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
