# Generated by Django 5.1.5 on 2025-08-09 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='last_heartbeat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
