# Generated by Django 5.1.5 on 2025-05-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'آیتم سبد خرید',
                'verbose_name_plural': 'آیتم\u200cهای سبد خرید',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('discount_percent', models.PositiveIntegerField(verbose_name='درصد تخفیف')),
                ('valid_from', models.DateTimeField(verbose_name='تاریخ شروع اعتبار')),
                ('valid_to', models.DateTimeField(verbose_name='تاریخ پایان اعتبار')),
                ('min_purchase', models.PositiveIntegerField(default=0, verbose_name='حداقل مبلغ خرید')),
                ('max_discount', models.PositiveIntegerField(default=0, verbose_name='حداکثر مبلغ تخفیف')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'آیتم لیست علاقه\u200cمندی\u200cها',
                'verbose_name_plural': 'آیتم\u200cهای لیست علاقه\u200cمندی\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
