# Generated by Django 5.1.5 on 2025-05-20 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
        ('products', '0005_alter_size_options_remove_color_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productinventory'),
        ),
    ]
