# Generated by Django 5.1.5 on 2025-09-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
