# Generated by Django 5.1.5 on 2025-05-17 09:09

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='فرمت\u200cهای مجاز: JPG, JPEG, PNG, GIF, WebP', upload_to='banners/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='فرمت\u200cهای مجاز: JPG, JPEG, PNG, GIF, WebP', upload_to=products.models.get_category_image_path, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='فرمت\u200cهای مجاز: JPG, JPEG, PNG, GIF, WebP', upload_to=products.models.get_product_image_path, verbose_name='تصویر'),
        ),
    ]
