# Generated by Django 5.1.5 on 2025-05-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_banner_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام رنگ')),
                ('code', models.CharField(help_text='مثال: #FF5733', max_length=10, verbose_name='کد رنگ')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام سایز')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایزها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.JSONField(default=dict, help_text='دیکشنری از موجودی هر ترکیب رنگ و سایز مانند {"S-سفید": 10, "M-سفید": 5}', verbose_name='موجودی بر اساس رنگ و سایز'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_adjustments',
            field=models.JSONField(default=dict, help_text='دیکشنری از تغییرات قیمت مانند {"S": 0, "M": 10000, "L": 20000}', verbose_name='تغییرات قیمت'),
        ),
    ]
