# Generated by Django 5.1.5 on 2025-05-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_size_options_remove_color_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='dimensions',
            field=models.CharField(blank=True, help_text='ابعاد (مثال: 30x40x10)', max_length=100),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='وزن به گرم'),
        ),
    ]
