# Generated by Django 5.1.5 on 2025-09-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_color_codes_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='hex_code_field',
        ),
        migrations.AddField(
            model_name='product',
            name='color_codes',
            field=models.JSONField(default=list, help_text='به صورت آرایه\u200cای از کدهای رنگ مانند ["#FFFFFF", "#000000", "#0000FF"]', verbose_name='کد رنگ\u200cها'),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.JSONField(default=list, help_text='به صورت آرایه\u200cای از رنگ\u200cها مانند ["سفید", "مشکی", "آبی"]', verbose_name='رنگ\u200cها'),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.JSONField(default=dict, help_text='دیکشنری از موجودی هر ترکیب رنگ و سایز مانند {"S-سفید": 10, "M-سفید": 5}', verbose_name='موجودی بر اساس رنگ و سایز'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_adjustments',
            field=models.JSONField(default=dict, help_text='دیکشنری از تغییرات قیمت مانند {"S": 0, "M": 10000, "L": 20000}', verbose_name='تغییرات قیمت'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(default=list, help_text='به صورت آرایه\u200cای از سایزها مانند ["S", "M", "L"]', verbose_name='سایزها'),
        ),
        migrations.DeleteModel(
            name='ProductQuestion',
        ),
    ]
